// Hero image mapping for blog posts
// Maps blog post slugs to their hero image URLs

export const heroImageMapping: Record<string, string> = {
  // Batch 1 - Featured Images (Entries 1-35)
  "why-summer-changes-your-dough": "/hero-images/why-summer-changes-your-dough.png",
  "proofing-yeasted-dough-guide": "/hero-images/proofing-yeasted-dough-guide.png",
  "blueberry-white-chocolate-chip-scones": "/hero-images/blueberry-white-chocolate-chip-scones.jpg",
  "bulk-fermentation": "/hero-images/bulk-fermentation.png",
  "this-keeps-it-simple-readable-and-keyword-friendly-you-could-add-with-cream-cheese-icing-if-you-want-it-more-specific-but-shorter-urls-are-usually-better-for-seo": "/hero-images/this-keeps-it-simple-readable-and-keyword-friendly-you-could-add-with-cream-cheese-icing-if-you-want-it-more-specific-but-shorter-urls-are-usually-better-for-seo.jpg",
  "hybrid-sourdough-sandwich-bread": "/hero-images/hybrid-sourdough-sandwich-bread.jpg",
  "the-loaf-and-the-lie": "/hero-images/the-loaf-and-the-lie.png",
  "ancient-grain-flour-baking-guide": "/hero-images/ancient-grain-flour-baking-guide.png",
  "the-sourdough-mama-artistic-sourdough-scoring": "/hero-images/the-sourdough-mama-artistic-sourdough-scoring.jpeg",
  "steam-for-sourdough-crust": "/hero-images/steam-for-sourdough-crust.png",
  "vietnamese-banh-mi-baguette": "/hero-images/vietnamese-banh-mi-baguette.webp",
  "rose-burns-bread-baker": "/hero-images/rose-burns-bread-baker.png",
  "homemade-hot-cross-buns%e2%9c%9d%ef%b8%8f": "/hero-images/homemade-hot-cross-buns%e2%9c%9d%ef%b8%8f.jpg",
  "marbled-blueberry-sourdough-recipe": "/hero-images/marbled-blueberry-sourdough-recipe.jpg",
  "member-spotlight-bella-artisan-bread": "/hero-images/member-spotlight-bella-artisan-bread.png",
  "is-sourdough-healthier-than-regular-bread": "/hero-images/is-sourdough-healthier-than-regular-bread.jpg",
  "member-spotlight-debbie-eckerstein": "/hero-images/member-spotlight-debbie-eckerstein.jpg",
  "henrys-blueberry-muffin-bread": "/hero-images/henrys-blueberry-muffin-bread.jpg",
  "priscilla-jolly-chocolate-cherry-sourdough-recipe": "/hero-images/priscilla-jolly-chocolate-cherry-sourdough-recipe.jpg",
  "the-magic-of-yeast-water": "/hero-images/the-magic-of-yeast-water.jpg",
  "brioche-bread-recipe": "/hero-images/brioche-bread-recipe.jpg",
  "sourdough-for-the-rest-of-us-free-download": "/hero-images/sourdough-for-the-rest-of-us-free-download.png",
  "blackberry-orange-galette": "/hero-images/blackberry-orange-galette.jpg",
  "bread-proofing-poke-test": "/hero-images/bread-proofing-poke-test.jpg",
  "crusty-white-bread-recipe": "/hero-images/crusty-white-bread-recipe.png",
  "donnas-baguette-recipe": "/hero-images/donnas-baguette-recipe.png",
  "flour-protein-content-guide": "/hero-images/flour-protein-content-guide.jpeg",
  "onion-poppy-seed-pletzel-recipe": "/hero-images/onion-poppy-seed-pletzel-recipe.jpg",
  "spelt-sourdough-bread": "/hero-images/spelt-sourdough-bread.jpg",
  "artisan-sourdough-bread": "/hero-images/artisan-sourdough-bread.jpg",
  "from-passion-to-profit-a-bakers-guide-to-market-success": "/hero-images/from-passion-to-profit-a-bakers-guide-to-market-success.webp",
  "rosemary-garlic-parmesan-bread": "/hero-images/rosemary-garlic-parmesan-bread.png",
  "versatile-market-yeast-dough": "/hero-images/versatile-market-yeast-dough.webp",
  "homemade-bagel-recipe": "/hero-images/homemade-bagel-recipe.jpg",
  "savory-irish-soda-bread": "/hero-images/savory-irish-soda-bread.jpg",
  
  // Batch 2 - Featured Images (Entries 36-70)
  "henrys-whole-wheat-sandwich-bread-2": "/hero-images/henrys-whole-wheat-sandwich-bread-2.jpg",
  "henrys-foolproof-sourdough-loaf-2": "/hero-images/henrys-foolproof-sourdough-loaf-2.jpg",
  "freshstart-challenge-sweet-rolls-with-stevia": "/hero-images/freshstart-challenge-sweet-rolls-with-stevia.jpg",
  "blueberry-peach-apple-bread": "/hero-images/blueberry-peach-apple-bread.jpeg",
  "yeast-for-baking-guide": "/hero-images/yeast-for-baking-guide.webp",
  "cold-proofing-bread-refrigerator-guide": "/hero-images/cold-proofing-bread-refrigerator-guide.webp",
  "north-dakota-caramel-rolls": "/hero-images/north-dakota-caramel-rolls.jpg",
  "how-to-get-dough-to-rise-in-a-cold-home-%f0%9f%a5%b6%f0%9f%8d%9e": "/hero-images/how-to-get-dough-to-rise-in-a-cold-home-%f0%9f%a5%b6%f0%9f%8d%9e.webp",
  "sourdough-baguettes": "/hero-images/sourdough-baguettes.webp",
  "ciabatta-bread-recipe": "/hero-images/ciabatta-bread-recipe.webp",
  "vietnamese-banh-mi": "/hero-images/vietnamese-banh-mi.webp",
  "double-cinnamon-rolls-with-a-festive-beetroot-twist": "/hero-images/double-cinnamon-rolls-with-a-festive-beetroot-twist.webp",
  "the-story-behind-my-challah": "/hero-images/the-story-behind-my-challah.webp",
  "%f0%9f%8e%84-warm-up-your-winter-with-apple-cinnamon-loaf": "/hero-images/%f0%9f%8e%84-warm-up-your-winter-with-apple-cinnamon-loaf.webp",
  "classic-christmas-panettone": "/hero-images/classic-christmas-panettone.jpg",
  "cinnamon-sugar-kuchen": "/hero-images/cinnamon-sugar-kuchen.jpg",
  "resilience-a-story-of-sourdough-and-hushpuppies": "/hero-images/resilience-a-story-of-sourdough-and-hushpuppies.webp",
  "southern-cornbread-dressing": "/hero-images/southern-cornbread-dressing.webp",
  "classic-bread-stuffing": "/hero-images/classic-bread-stuffing.webp",
  "thanksgiving-debate-dressing-vs-stuffing-and-the-tradition-of-the-cousin-walk": "/hero-images/thanksgiving-debate-dressing-vs-stuffing-and-the-tradition-of-the-cousin-walk.webp",
  "a-thanksgiving-lifesaver": "/hero-images/a-thanksgiving-lifesaver.jpg",
  "baking-bread-at-altitude": "/hero-images/baking-bread-at-altitude.webp",
  // Note: "so-i-ended-up-with-21-bananas" has no image (null values)
  "shokupan-japanese-milk-bread": "/hero-images/shokupan-japanese-milk-bread.webp",
  "blog-subscriber-challenge-giveaway": "/hero-images/blog-subscriber-challenge-giveaway.webp",
  "henrys-crusty-french-bread": "/hero-images/henrys-crusty-french-bread.webp",
  "herb-infused-focaccia": "/hero-images/herb-infused-focaccia.webp",
  "holiday-cranberry-walnut-sourdough-recipe": "/hero-images/holiday-cranberry-walnut-sourdough-recipe.jpg",
  "dutch-oven-vs-baking-shell": "/hero-images/dutch-oven-vs-baking-shell.jpg",
  "sourdough-challah-orange": "/hero-images/sourdough-challah-orange.webp",
  "get-ready-tasty-bread-baking-ideas-for-the-holidays": "/hero-images/get-ready-tasty-bread-baking-ideas-for-the-holidays.jpg",
  "how-to-store-your-bread": "/hero-images/how-to-store-your-bread.webp",
  "yeasted-cheddar-basil-loaf": "/hero-images/yeasted-cheddar-basil-loaf.jpg",
  "why-measuring-flour-with-a-digital-scale-can-transform-your-baking": "/hero-images/why-measuring-flour-with-a-digital-scale-can-transform-your-baking.png",
  "how-to-determine-the-protein-content-in-flour-for-better-baking": "/hero-images/how-to-determine-the-protein-content-in-flour-for-better-baking.jpg",
  
  // Batch 3 - Featured Images (Entries 71-105)
  "mastering-the-basics": "/hero-images/mastering-the-basics.jpg",
  "sourdough-starter-guide": "/hero-images/sourdough-starter-guide.png",
  "october-challenge-breadjourney": "/hero-images/october-challenge-breadjourney.jpg",
  "bewitching-bread": "/hero-images/bewitching-bread.png",
  "week-3-kickuplunch-challenge": "/hero-images/week-3-kickuplunch-challenge.jpg",
  "the-art-and-science-of-storing-bread-keeping-your-loaf-fresh-and-delicious": "/hero-images/the-art-and-science-of-storing-bread-keeping-your-loaf-fresh-and-delicious.png",
  "%f0%9f%a5%96-semi-annual-report-september-15-2024-%f0%9f%a5%96": "/hero-images/%f0%9f%a5%96-semi-annual-report-september-15-2024-%f0%9f%a5%96.jpg",
  "kickuplunch-week-2": "/hero-images/kickuplunch-week-2.webp",
  "mastering-cinnamon-swirl-bread": "/hero-images/mastering-cinnamon-swirl-bread.webp",
  "grilled-chicken-and-pesto-focaccia-sandwiches-a-king-arthur-flour-masterpiece": "/hero-images/grilled-chicken-and-pesto-focaccia-sandwiches-a-king-arthur-flour-masterpiece.png",
  "preparing-for-your-state-fair-a-guide-for-first-time-bread-contestants": "/hero-images/preparing-for-your-state-fair-a-guide-for-first-time-bread-contestants.webp",
  "exploring-flour-types-from-all-purpose-to-climate-friendly-options-baking-innovation": "/hero-images/exploring-flour-types-from-all-purpose-to-climate-friendly-options-baking-innovation.jpeg",
  "strawberry-rita-yeasted-bread-recipe": "/hero-images/strawberry-rita-yeasted-bread-recipe.jpg",
  "baking-great-bread-at-home-quiz": "/hero-images/baking-great-bread-at-home-quiz.jpeg",
  "pasta-madre-challenge-elevate-your-baking": "/hero-images/pasta-madre-challenge-elevate-your-baking.jpg",
  "mastering-sourdough-insights-from-my-baking-journey": "/hero-images/mastering-sourdough-insights-from-my-baking-journey.png",
  "introducing-your-new-baking-assistant-meet-rachel": "/hero-images/introducing-your-new-baking-assistant-meet-rachel.png",
  "brioche-pasta-madre-recipe-experiment": "/hero-images/brioche-pasta-madre-recipe-experiment.webp",
  "cheddar-jalapeno-loaf-recipe": "/hero-images/cheddar-jalapeno-loaf-recipe.jpg",
  "join-our-august-challenge": "/hero-images/join-our-august-challenge.png",
  "mastering-gluten-free-bread": "/hero-images/mastering-gluten-free-bread.jpg",
  "summer-fruit-quick-bread": "/hero-images/summer-fruit-quick-bread.jpg",
  "focaccia-crafting-aromatic-herb-infused-bread": "/hero-images/focaccia-crafting-aromatic-herb-infused-bread.jpg",
  "how-to-become-a-much-better-baker": "/hero-images/how-to-become-a-much-better-baker.jpg",
  "blueberry-brown-sugar-cinnamon-focaccia": "/hero-images/blueberry-brown-sugar-cinnamon-focaccia.jpg",
  "the-art-of-making-enriched-breads": "/hero-images/the-art-of-making-enriched-breads.jpg",
  "the-art-of-choosing-the-right-proofing-basket": "/hero-images/the-art-of-choosing-the-right-proofing-basket.jpg",
  "cream-cheese-blueberry-danish-walnut-streusel": "/hero-images/cream-cheese-blueberry-danish-walnut-streusel.jpg",
  "mastering-dough-hydration-guide": "/hero-images/mastering-dough-hydration-guide.jpg",
  "henrys-sourdough-bread-making-process-a-straightforward-guide": "/hero-images/henrys-sourdough-bread-making-process-a-straightforward-guide.jpg",
  "sourdough-baking-henry-hunter": "/hero-images/sourdough-baking-henry-hunter.jpg",
  "sourdough-discard-pretzels": "/hero-images/sourdough-discard-pretzels.jpeg",
  "sourdough-discard-bread": "/hero-images/sourdough-discard-bread.jpeg",
  "exploring-the-world-of-flour": "/hero-images/exploring-the-world-of-flour.jpeg",
  "homemade-multigrain-bread": "/hero-images/homemade-multigrain-bread.jpg",
  
  // Batch 4 - Featured Images (Entries 106-140)
  "traditional-hot-cross-buns-easter-recipe": "/hero-images/traditional-hot-cross-buns-easter-recipe.jpg",
  "starting-a-sourdough-starter-interview-henry": "/hero-images/starting-a-sourdough-starter-interview-henry.jpg",
  "sourdough-discard-challah-bread-2": "/hero-images/sourdough-discard-challah-bread-2.jpg",
  "sourdough-discard-challah-bread": "/hero-images/sourdough-discard-challah-bread.jpg",
  "sourdough-discard-coffee-cake": "/hero-images/sourdough-discard-coffee-cake.jpeg",
  "dehydrating-your-sourdough-starter": "/hero-images/dehydrating-your-sourdough-starter.jpg",
  "mastering-flour-varieties-unlocking-baking-perfection%f0%9f%8c%be": "/hero-images/mastering-flour-varieties-unlocking-baking-perfection%f0%9f%8c%be.jpg",
  // Note: "hydration-calculator" has no image (empty values)
  "discovering-sourdough": "/hero-images/discovering-sourdough.webp",
  "knead-to-know-sourdough-basics": "/hero-images/knead-to-know-sourdough-basics.jpg",
  "the-science-behind-perfect-crust": "/hero-images/the-science-behind-perfect-crust.webp",
  "henrys-foolproof-sourdough-loaf": "/hero-images/henrys-foolproof-sourdough-loaf.jpg",
  "the-ultimate-dinner-rolls": "/hero-images/the-ultimate-dinner-rolls.jpg",
  "heavy-cream-cinnamon-rolls": "/hero-images/heavy-cream-cinnamon-rolls.jpeg",
  "in-bethlehems-depths-where-old-tales-echo": "/hero-images/in-bethlehems-depths-where-old-tales-echo.jpg",
  "the-bread-revolution": "/hero-images/the-bread-revolution.jpg",
  "enhancing-sourdough-with-cinnamon-a-bakers-guide": "/hero-images/enhancing-sourdough-with-cinnamon-a-bakers-guide.jpg",
  "cardamom-infused-cinnamon-rolls-with-yudane-method": "/hero-images/cardamom-infused-cinnamon-rolls-with-yudane-method.jpg",
  "homemade-white-sandwich-bread": "/hero-images/homemade-white-sandwich-bread.jpeg",
  "bread-science": "/hero-images/bread-science.webp",
  "congratulations-to-amy-orwick-wheatley": "/hero-images/congratulations-to-amy-orwick-wheatley.jpg",
  "henrys-crusty-white-bread-recipe": "/hero-images/henrys-crusty-white-bread-recipe.webp",
  "homemade-hoagie-rolls-recipe": "/hero-images/homemade-hoagie-rolls-recipe.jpg",
  // Note: "icebox-butterhorns" has no image (empty values)
  // Note: "rolling-in-dough" has no image (empty values)
  "holiday-pumpkin-bread-pudding-with-spiced-apple-cider-butter-sauce-and-candied-pecans": "/hero-images/holiday-pumpkin-bread-pudding-with-spiced-apple-cider-butter-sauce-and-candied-pecans.jpeg",
  "festive-christmas-banana-bread": "/hero-images/festive-christmas-banana-bread.jpg",
  "traditional-british-christmas-pudding": "/hero-images/traditional-british-christmas-pudding.jpeg",
  "bread-pudding-recipe-a-cozy-thanksgiving-treat-%f0%9f%a6%83%f0%9f%8d%82": "/hero-images/bread-pudding-recipe-a-cozy-thanksgiving-treat-%f0%9f%a6%83%f0%9f%8d%82.jpeg",
  "sourdough-artisan-bread-stuffing-a-thanksgiving-classic-%f0%9f%a6%83%f0%9f%8c%bf": "/hero-images/sourdough-artisan-bread-stuffing-a-thanksgiving-classic-%f0%9f%a6%83%f0%9f%8c%bf.jpeg",
  "sunflower-bloom-bread": "/hero-images/sunflower-bloom-bread.jpg",
  "banana-bread": "/hero-images/banana-bread.jpg",
  "blueberry-cinnamon-rolls": "/hero-images/blueberry-cinnamon-rolls.jpg",
  "your-first-classic-sourdough-loaf": "/hero-images/your-first-classic-sourdough-loaf.jpg",
  "vegan-apple-bread": "/hero-images/vegan-apple-bread.jpg",
  
  // Batch 5 - Featured Images (Entries 141-175)
  "%f0%9f%8d%9e-the-secret-life-of-bread": "/hero-images/%f0%9f%8d%9e-the-secret-life-of-bread.jpg",
  "homemade-brown-and-serve-rolls": "/hero-images/homemade-brown-and-serve-rolls.jpeg",
  "baking-bread": "/hero-images/baking-bread.jpg",
  "baking-beyond-borders-a-conversation-with-yoshie-horie": "/hero-images/baking-beyond-borders-a-conversation-with-yoshie-horie.jpg",
  "the-harvest-loaf-3": "/hero-images/the-harvest-loaf-3.jpg",
  "coffee-scrolls": "/hero-images/coffee-scrolls.jpg",
  "fruit-and-nut-holiday-bread": "/hero-images/fruit-and-nut-holiday-bread.jpg",
  "the-harvest-loaf": "/hero-images/the-harvest-loaf.jpg",
  "orange-cinnamon-sweet-rolls": "/hero-images/orange-cinnamon-sweet-rolls.jpg",
  "julekaka": "/hero-images/julekaka.jpg",
  "sourdough-festive-fruit-bun-with-vanilla-frosting": "/hero-images/sourdough-festive-fruit-bun-with-vanilla-frosting.jpg",
  "christmas-stollen-2": "/hero-images/christmas-stollen-2.jpg",
  "holiday-monkey-bread": "/hero-images/holiday-monkey-bread.jpg",
  "cranberry-walnut-sourdough-loaf": "/hero-images/cranberry-walnut-sourdough-loaf.jpg",
  "cranberry-vanilla-cinnamon-swirl-bread": "/hero-images/cranberry-vanilla-cinnamon-swirl-bread.jpg",
  "baked-brie-and-bread-wreath": "/hero-images/baked-brie-and-bread-wreath.jpg",
  "yeasted-dinner-rolls": "/hero-images/yeasted-dinner-rolls.jpg",
  "pan-de-muerto": "/hero-images/pan-de-muerto.jpg",
  "sourdough-dinner-rolls": "/hero-images/sourdough-dinner-rolls.png",
  // Note: "our-groups-stance-on-sourdough-bread-and-commercial-yeast" has no image (empty values)
  "classic-white-ssandwich-breads": "/hero-images/classic-white-ssandwich-breads.webp",
  "chocolate-babka-recipe-2": "/hero-images/chocolate-babka-recipe-2.jpg",
  "eggnog-bread": "/hero-images/eggnog-bread.jpg",
  "rustic-apple-focaccia-2": "/hero-images/rustic-apple-focaccia-2.jpg",
  "holiday-star-cinnamon-roll-bread": "/hero-images/holiday-star-cinnamon-roll-bread.jpg",
  "%f0%9f%8d%8f-baking-great-bread-with-dehydrated-apples-tips-and-recipes-%f0%9f%8d%9e": "/hero-images/%f0%9f%8d%8f-baking-great-bread-with-dehydrated-apples-tips-and-recipes-%f0%9f%8d%9e.jpg",
  // Note: "the-great-hooch-debate-2-0" has no image (empty values)
  "gingerbread": "/hero-images/gingerbread.jpg",
  "2172": "/hero-images/2172.jpg",
  "christmas-stollen": "/hero-images/christmas-stollen.jpg",
  "a-fall-slowdown-for-vitale": "/hero-images/a-fall-slowdown-for-vitale.jpg",
  "mastering-sourdough-in-chilly-weather-tips-for-homemakers-%e2%9d%84%ef%b8%8f": "/hero-images/mastering-sourdough-in-chilly-weather-tips-for-homemakers-%e2%9d%84%ef%b8%8f.jpg",
  "my-bread-journey-to-panettone-a-tale-of-triumph-and-ingenuity": "/hero-images/my-bread-journey-to-panettone-a-tale-of-triumph-and-ingenuity.jpg",
  "journey-through-the-world-of-bread-with-us": "/hero-images/journey-through-the-world-of-bread-with-us.jpg",
  "understanding-gluten-gluten-sensitivity-and-celiac-disease-a-bakers-guide": "/hero-images/understanding-gluten-gluten-sensitivity-and-celiac-disease-a-bakers-guide.webp",
  
  // Batch 6 - Featured Images (Entries 176-210)
  "the-science-of-sourdough-how-flour-choices-affect-your-bread": "/hero-images/the-science-of-sourdough-how-flour-choices-affect-your-bread.jpg",
  "recipe-sourdough-pumpkin-bread": "/hero-images/recipe-sourdough-pumpkin-bread.jpg",
  "recipe-yeasted-pumpkin-shaped-bread": "/hero-images/recipe-yeasted-pumpkin-shaped-bread.jpg",
  "the-essential-role-of-knife-sharpening-in-your-bread-baking-journey": "/hero-images/the-essential-role-of-knife-sharpening-in-your-bread-baking-journey.jpg",
  "yeast-water-magic": "/hero-images/yeast-water-magic.jpg",
  "bread-baking-glossary": "/hero-images/bread-baking-glossary.png",
  "expand-your-bread-creativity-dehydrated-fruits-and-more": "/hero-images/expand-your-bread-creativity-dehydrated-fruits-and-more.jpg",
  "navigating-a-rye-bread": "/hero-images/navigating-a-rye-bread.jpg",
  "in-the-interplay-of-science-and-faith-the-quantum-nature-of-creation": "/hero-images/in-the-interplay-of-science-and-faith-the-quantum-nature-of-creation.jpg",
  "mastering-the-art-of-challah": "/hero-images/mastering-the-art-of-challah.jpg",
  "baking-in-hot-weather": "/hero-images/baking-in-hot-weather.jpg",
  "baking-with-fresh-fruits-elevate-your-bread-with-seasonal-delights": "/hero-images/baking-with-fresh-fruits-elevate-your-bread-with-seasonal-delights.jpg",
  "vitales-sourdough-summer": "/hero-images/vitales-sourdough-summer.jpg",
  "starter-guide-for-beginners%f0%9f%8d%9e": "/hero-images/starter-guide-for-beginners%f0%9f%8d%9e.jpg",
  "the-art-of-dough-scoring": "/hero-images/the-art-of-dough-scoring.jpg",
  "vitales-tale": "/hero-images/vitales-tale.jpg",
  "%f0%9f%8d%9e-to-salt-or-not-to-salt": "/hero-images/%f0%9f%8d%9e-to-salt-or-not-to-salt.jpg",
  "%f0%9f%93%a3%f0%9f%8d%9e-understanding-the-bakers-percentage": "/hero-images/%f0%9f%93%a3%f0%9f%8d%9e-understanding-the-bakers-percentage.jpg",
  // Note: "%f0%9f%8d%9e-henrys-crusty-white-bread-recipe" has no image (empty values)
  "henrys-whole-wheat-sandwich-bread": "/hero-images/henrys-whole-wheat-sandwich-bread.jpg",
  "unveiling-the-sacred-tradition-of-challah": "/hero-images/unveiling-the-sacred-tradition-of-challah.jpg",
  "pre-ferment": "/hero-images/pre-ferment.jpg",
  "navigating-the-sourdough-journey-hooch-hydration-and-more": "/hero-images/navigating-the-sourdough-journey-hooch-hydration-and-more.jpeg",
  "%f0%9f%8d%9e-sourdough-starter-guide-for-beginners-%f0%9f%8d%9e": "/hero-images/%f0%9f%8d%9e-sourdough-starter-guide-for-beginners-%f0%9f%8d%9e.jpg",
  "title-%f0%9f%8d%9e-mastering-dough-rise-a-foolproof-guide-%f0%9f%93%88": "/hero-images/title-%f0%9f%8d%9e-mastering-dough-rise-a-foolproof-guide-%f0%9f%93%88.jpg",
  // Note: "subject-apologies-for-the-broken-homepage-great-content-inside" has no image (empty values)
  "the-great-hooch-debate-2-0-a-deeper-dive-into-sourdough-science-%f0%9f%8d%9e%f0%9f%a7%aa": "/hero-images/the-great-hooch-debate-2-0-a-deeper-dive-into-sourdough-science-%f0%9f%8d%9e%f0%9f%a7%aa.jpg",
  "the-great-hooch-debate": "/hero-images/the-great-hooch-debate.jpg",
  "utah-scones-aka-indian-fry-bread": "/hero-images/utah-scones-aka-indian-fry-bread.jpg",
  // Note: Multiple entries (205-208, 210) have no images (empty values)
  "sourdough-baking-workshop-itinerary": "/hero-images/sourdough-baking-workshop-itinerary.jpg",
};

// Function to get hero image URL by slug
export const getHeroImageBySlug = (slug: string): string | null => {
  return heroImageMapping[slug] || null;
};

// Function to get hero image URL with fallback
export const getHeroImageWithFallback = (slug: string, fallback?: string): string => {
  return heroImageMapping[slug] || fallback || '/lovable-uploads/bd157eb8-d847-4f54-913a-8483144ecb46.png';
};