import { processCSVData, mergeProducts, generateProductsJSON, type CSVProduct } from './affiliateProductProcessor';

// Parse the CSV data from the user's master list
const csvData: CSVProduct[] = [
  {
    id: "brod--taylor-apron",
    name: "Brod & Taylor Apron",
    description: "Durable, professional-quality apron designed for everyday baking and cooking with comfort and protection in mind.",
    brand: "Brod & Taylor",
    category: "accessories",
    price: "60",
    affiliate_link: "https://collabs.shop/akcwv4",
    keywords: "apron,kitchen,baking,bread,cooking,professional,durable,home baking,kitchen apparel,kitchen tool",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/APRONPO73716453-front_1024x.jpg?v=1715621552",
    utm_params: ""
  },
  {
    id: "challenger-parchment-papers",
    name: "Challenger Parchment Papers",
    description: "Pre-cut parchment papers that fit perfectly in the Challenger Bread Pan for easy bread release and cleanup.",
    brand: "Challenger Breadware",
    category: "accessories",
    price: "",
    affiliate_link: "https://challengerbreadware.com/?ref=henryhunterjr",
    keywords: "parchment paper,challenger,pre-cut,bread baking,non-stick,easy release,cleanup,baking paper,convenience,bread making",
    regions: "US,EU,CA",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "https://challengerbreadware.com/wp-content/uploads/2020/02/Challenger-Breadware-Media-Kit-Logo-Color.jpg",
    utm_params: ""
  },
  {
    id: "classic-vg2-knife-sharpener",
    name: "Classic VG2 Knife Sharpener",
    description: "Professional-grade knife sharpener to keep bread and kitchen knives at peak performance for precise cutting and slicing.",
    brand: "Brod & Taylor",
    category: "accessories",
    price: "59",
    affiliate_link: "https://collabs.shop/lifdzg",
    keywords: "knife sharpener,VG2,kitchen tool,bread,slicing,sharp,professional,cooking,prep,home baking",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/ks_610_1_1024x.jpg?v=1645470566",
    utm_params: ""
  },
  {
    id: "spice--coffee-grinder",
    name: "Spice & Coffee Grinder",
    description: "Compact, powerful grinder for freshly milled spices and coffee beans, enhancing flavor in baking and brewing.",
    brand: "Brod & Taylor",
    category: "accessories",
    price: "24.95",
    affiliate_link: "https://collabs.shop/ve9hzn",
    keywords: "grinder,spice,coffee,kitchen tool,bread,pastry,freshly milled,flavor,baking,home baking",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/1_1024x.jpg?v=1665423750",
    utm_params: ""
  },
  {
    id: "water-kettle-and-french-press",
    name: "Water Kettle and French Press",
    description: "Combined water kettle and French press for brewing coffee or tea, ideal for the complete baking and beverage experience.",
    brand: "Collabs",
    category: "accessories",
    price: "117.53",
    affiliate_link: "https://collabs.shop/b8bht0",
    keywords: "kettle,french press,coffee,tea,kitchen appliance,water heating,beverage,home baking,bread prep,kitchen tool",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "",
    utm_params: ""
  },
  {
    id: "wire-monkey-lame-holster",
    name: "Wire Monkey Lame Holster",
    description: "Upcycled leather holster for safe storage and stylish carrying of Wire Monkey lames, combining practicality with sustainability.",
    brand: "Wire Monkey",
    category: "accessories",
    price: "",
    affiliate_link: "https://bit.ly/3QFQek8",
    keywords: "lame holster,wire monkey,leather holster,storage,safety,upcycled,sustainable,bread tools,organization,scoring accessories",
    regions: "US,EU,CA",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://wiremonkey.com/cdn/shop/files/WM_logo_Registered_TM_Transparent_high_res_da96b866-cd14-4259-b27e-5314d936fad1_256x256-min_1200x1200.png?v=1680623880",
    utm_params: ""
  },
  {
    id: "baking-shell-batard--steel",
    name: "Baking Shell (Batard) & Steel",
    description: "Set combining lightweight aluminum batard shell and baking steel for optimal oval loaf baking with superior heat retention.",
    brand: "Brod & Taylor",
    category: "baking",
    price: "148",
    affiliate_link: "https://collabs.shop/noauwh",
    keywords: "baking shell,batard,baking steel,steam baking,sourdough,bread,crust,oven,artisan bread,home baking",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/A7R05283ss-240516_1024x.jpg?v=1724867128",
    utm_params: ""
  },
  {
    id: "baking-shell-boule",
    name: "Baking Shell (Boule)",
    description: "Lightweight aluminum shell designed to trap steam for professional-quality round loaves with excellent crust development.",
    brand: "Brod & Taylor",
    category: "baking",
    price: "79",
    affiliate_link: "https://collabs.shop/jveyfn",
    keywords: "baking shell,boule,steam baking,crust,sourdough,bread,oven,baking tool,aluminum,home baking",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/A7R05289-240516_1024x.jpg?v=1721939220",
    utm_params: ""
  },
  {
    id: "baking-shell-boule--steel",
    name: "Baking Shell (Boule) & Steel",
    description: "Set featuring boule-shaped aluminum baking shell and baking steel for exceptional round loaf baking performance.",
    brand: "Brod & Taylor",
    category: "baking",
    price: "148",
    affiliate_link: "https://collabs.shop/g9yxme",
    keywords: "baking shell,boule,baking steel,steam baking,sourdough,bread,crust,oven,artisan bread,home baking",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/Boule_Shell_and_Steel_1024x.jpg?v=1726780218",
    utm_params: ""
  },
  {
    id: "bread-steel",
    name: "Bread Steel",
    description: "Heavy-duty baking steel for home ovens providing excellent heat retention and even baking for crispy crusts on bread and pizza.",
    brand: "Brod & Taylor",
    category: "baking",
    price: "69",
    affiliate_link: "https://collabs.shop/qw7dzp",
    keywords: "baking steel,bread,pizza,heat retention,oven spring,crust,baking,pastry,artisan bread,kitchen tool",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/A7R06654_1024x.jpg?v=1689971635",
    utm_params: ""
  },
  {
    id: "sahara-folding-dehydrator",
    name: "Sahara Folding Dehydrator",
    description: "Space-saving dehydrator that folds to 1/3 size for storage while drying fruits, herbs, and sourdough starter with precise temperature control.",
    brand: "Brod & Taylor",
    category: "dehydrating",
    price: "199",
    affiliate_link: "https://collabs.shop/94zxfe",
    keywords: "dehydrator,food drying,herbs,fruit,starter preservation,folding appliance,kitchen gadget,preservation,snack making,baking prep",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/dr_710_1S_1024x.jpg?v=1637365834",
    utm_params: ""
  },
  {
    id: "baking-tools-starter-kit",
    name: "Baking Tools Starter Kit",
    description: "Curated kit for beginner sourdough bakers including bench scraper, lame, and essential tools for bread making success.",
    brand: "Brod & Taylor",
    category: "kits",
    price: "56.41",
    affiliate_link: "https://collabs.shop/7k4ksj",
    keywords: "starter kit,baking tools,sourdough,bread,lame,bench scraper,beginner,artisan bread,home baking,kitchen kit",
    regions: "US,EU",
    featured: "TRUE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/Whisk_Scale_BenchKnife_Bundle_1.1_1024x.jpg?v=1722547521",
    utm_params: ""
  },
  {
    id: "modkitchn-baking--storing-duo",
    name: "ModKitchn Baking & Storing Duo",
    description: "Bundle featuring classic round sling and reusable bread bags - everything needed for effortless baking and long-lasting bread storage.",
    brand: "ModKitchn",
    category: "kits",
    price: "",
    affiliate_link: "https://modkitchn.com/discount/BAKINGGREATBREAD10",
    keywords: "baking bundle,modkitchn,bread sling,storage bags,complete solution,home baking,bread making,sourdough kit,baking essentials,kitchen bundle",
    regions: "US,CA",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://modkitchn.com/cdn/shop/files/Untitled_design-11_22003064-f3ad-4218-8e0e-ea13b9683ee0.png?height=628&pad_color=ffffff&v=1752200061&width=1200",
    utm_params: ""
  },
  {
    id: "high-capacity-baking-scale",
    name: "High Capacity Baking Scale",
    description: "Sturdy, accurate scale designed for weighing larger dough batches with professional precision for serious home bakers.",
    brand: "Brod & Taylor",
    category: "measuring",
    price: "24.95",
    affiliate_link: "https://collabs.shop/hvryn6",
    keywords: "baking scale,high capacity,precision,weighing,bread,dough,kitchen tool,measurement,artisan bread,home baking",
    regions: "US,EU",
    featured: "TRUE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/hk320_knockoutbatteries_1024x.jpg?v=1673886851",
    utm_params: ""
  },
  {
    id: "precision-kitchen--coffee-scale-with-timer",
    name: "Precision Kitchen & Coffee Scale with Timer",
    description: "Compact scale with built-in timer for precise weighing of coffee, flour, and ingredients with professional accuracy.",
    brand: "Brod & Taylor",
    category: "measuring",
    price: "24.95",
    affiliate_link: "https://collabs.shop/cuut37",
    keywords: "kitchen scale,coffee scale,timer,precision,weighing,baking,bread,starter,measurement,kitchen tool",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/A7R04362_screenadded_sm_1024x.jpg?v=1665689187",
    utm_params: ""
  },
  {
    id: "dough-whisk",
    name: "Dough Whisk",
    description: "Classic tool for gentle, efficient mixing of dough without overworking, perfect for initial incorporation of ingredients.",
    brand: "Brod & Taylor",
    category: "mixing",
    price: "18.95",
    affiliate_link: "https://collabs.shop/6jalk7",
    keywords: "dough whisk,mixing,bread,pizza,pastry,kitchen tool,home baking,artisan bread,baking,dough",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/hk100_1_1024x.jpg?v=1646933306",
    utm_params: ""
  },
  {
    id: "folding-proofer--slow-cooker",
    name: "Folding Proofer & Slow Cooker",
    description: "Dual-function appliance that maintains ideal dough fermentation temperatures and functions as a slow cooker for versatile kitchen use.",
    brand: "Brod & Taylor",
    category: "proofing",
    price: "219",
    affiliate_link: "https://collabs.shop/vutgu8",
    keywords: "proofer,slow cooker,bread proofing,fermentation,yogurt,culturing,bread,baking,temperature control,kitchen appliance",
    regions: "US,EU",
    featured: "TRUE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/A7R00473_v4-230329_sm_1024x.jpg?v=1680127821",
    utm_params: ""
  },
  {
    id: "sourdough-home",
    name: "Sourdough Home",
    description: "Specialized temperature-controlled container that maintains optimal sourdough starter conditions with precise temperature management for consistent fermentation.",
    brand: "Brod & Taylor",
    category: "proofing",
    price: "119",
    affiliate_link: "https://collabs.shop/bnlqi7",
    keywords: "sourdough starter,fermentation,temperature control,starter proofer,bread,baking,home baking,starter maintenance,ferment,bread making",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/products/SourdoughHome_739cf2ce-a19f-46ea-908c-1e74da4afc34_1024x.jpg?v=1681336080",
    utm_params: ""
  },
  {
    id: "bench-knife",
    name: "Bench Knife",
    description: "Multipurpose scraper essential for shaping, dividing, and moving dough with precision in bread making and pastry work.",
    brand: "Brod & Taylor",
    category: "shaping",
    price: "18.95",
    affiliate_link: "https://collabs.shop/8vcnxu",
    keywords: "bench knife,dough scraper,bread shaping,pastry,baking,kitchen tool,dough,dividing,home baking,artisan bread",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/A7R06102-240524_1024x.jpg?v=1721757722",
    utm_params: ""
  },
  {
    id: "folding-dough-sheeter-155",
    name: "Folding Dough Sheeter 15.5\"",
    description: "Heavy-duty, foldable dough sheeter for rolling laminated doughs and achieving consistent thickness for pastries and breads.",
    brand: "Brod & Taylor",
    category: "shaping",
    price: "850",
    affiliate_link: "https://collabs.shop/g4nf7i",
    keywords: "dough sheeter,laminated dough,rolling,pastry,bread,baking,kitchen tool,professional,home baking,flattening",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/A7R02825-230808_2400px_49863fcb-c52f-4f21-8ec6-84ecc4533b6e_1024x.jpg?v=1714579978",
    utm_params: ""
  },
  {
    id: "cordless-vacuum-sealer",
    name: "Cordless Vacuum Sealer",
    description: "Portable vacuum sealer for preserving flour, starter, and par-baked goods with cordless convenience and freshness protection.",
    brand: "Brod & Taylor",
    category: "storage",
    price: "129",
    affiliate_link: "https://collabs.shop/rbhadw",
    keywords: "vacuum sealer,cordless,food storage,preservation,bread,starter,kitchen gadget,freshness,home baking,ingredient storage",
    regions: "US,EU",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://brodandtaylor.com/cdn/shop/files/A7R06016-231017copy_1024x.jpg?v=1706821317",
    utm_params: ""
  },
  {
    id: "holland-bowl-mill-wooden-bowl",
    name: "Holland Bowl Mill Wooden Bowl",
    description: "I use and recommend Holland Bowl Mill's hand-turned wooden bowls for mixing dough and serving with style. Each one is American-made and crafted to last generations. Use code BREADLOVE for a discount at checkout.",
    brand: "Holland Bowl Mill",
    category: "mixing",
    price: "",
    affiliate_link: "https://www.hollandbowlmill.com/?wpam_id=2665",
    keywords: "wooden bowl,mixing,dough,serving,american made,handcrafted,kitchen bowl,bread making,artisan,home baking",
    regions: "",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "https://hollandbowlmill.com/wp-content/uploads/2025/03/Franklin.webp",
    utm_params: ""
  },
  {
    id: "sour-house-dough-bed",
    name: "Sour House Dough Bed",
    description: "The Dough Bed is the perfect proofing mat—insulated, breathable, and big enough for two baskets. I use it every bake. Get yours at Sour House with code BREADLOVE for a discount.",
    brand: "Sour House",
    category: "proofing",
    price: "",
    affiliate_link: "https://sourhouse.co/?ref=breadlove",
    keywords: "dough bed,proofing mat,insulated,breathable,bread proofing,sourdough,fermentation,baking mat,kitchen tool,home baking",
    regions: "",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "http://sourhouse.co/cdn/shop/files/link_to_sourhouse.co_3.jpg?v=1671640628",
    utm_params: ""
  },
  {
    id: "vitale-dehydrated-sourdough-starter",
    name: "Vitale Dehydrated Sourdough Starter",
    description: "You will be baking bread in 3-Days with Vitale Sourdough Starter - Let's Break Bread, Not Traditions. 5 out of 5 stars. Ships from South Carolina. Returns & exchanges accepted. With your purchase, you're receiving 40 grams of premium dehydrated sourdough starter. Perfect for baking today, saving some for a rainy day, or sharing the joy of bread-making with friends.",
    brand: "Etsy",
    category: "starter",
    price: "",
    affiliate_link: "https://vitalesourdoughco.etsy.com",
    keywords: "sourdough starter,dehydrated,vitale,3-day bread,starter culture,home baking,bread making,fermentation,artisan bread,baking supplies",
    regions: "",
    featured: "FALSE",
    seasonal_tags: "",
    image_url: "https://i.etsystatic.com/40620987/r/isla/b253e3/69866996/isla_500x500.69866996_n2ui5tce.jpg",
    utm_params: ""
  }
];

export { csvData };