-- Insert seasonal recipes into the database
INSERT INTO public.recipes (title, slug, folder, tags, is_public, user_id, data, image_url) VALUES
('Classic White Sandwich Bread', 'classic-white-sandwich-bread', 'Seasonal', ARRAY['winter', 'sandwich', 'lean dough', 'beginner', 'everyday'], true, '66d74ee0-b848-4b4d-b37c-6197d5d01d66', 
'{"season": "Winter", "holidays": [], "featuredDates": {"start": "01-01", "end": "03-31"}, "category": ["yeast bread"], "occasion": ["everyday"], "prepTime": "0 hours 20 minutes", "bakeTime": "0 hours 35 minutes", "totalTime": "2 hours 50 minutes", "difficulty": "beginner", "yield": "1 loaf", "ingredients": ["Bread Flour: 600g (5 cups)", "Warm Water: 375ml (1 1/2 cups)", "Active Dry Yeast: 7g (2 1/4 tsp)", "Sugar: 15g (1 tbsp)", "Salt: 10g (2 tsp)", "Butter: 45g (3 tbsp), softened"], "method": ["Combine warm water (95–100°F), yeast and sugar; let froth 5–10 min.", "Mix flour, salt, butter; add yeast mix into a shaggy dough.", "Knead 8–10 min until smooth.", "Let rise 1–2 hr (up to 3 hr in cold kitchen) until doubled.", "Shape, proof 45–60 min until 1\" above pan rim.", "Bake at 375°F for 30–35 min until golden.", "Cool on wire rack before slicing."], "notes": "In cold kitchens, use warmer water (100–105°F) and proof near warm appliance; add extra water if dough feels dry.", "equipment": ["9×5-inch loaf pan", "mixing bowl", "oven thermometer"]}', null),

('Henrys Crusty White Bread', 'henrys-crusty-white-bread', 'Seasonal', ARRAY['crusty', 'artisan', 'winter', 'intermediate', 'everyday'], true, '66d74ee0-b848-4b4d-b37c-6197d5d01d66',
'{"season": "Winter", "holidays": [], "featuredDates": {"start": "01-01", "end": "03-31"}, "category": ["yeast bread"], "occasion": ["everyday"], "prepTime": "0 hours 20 minutes", "bakeTime": "0 hours 30 minutes", "totalTime": "2 hours 30 minutes", "difficulty": "intermediate", "yield": "1 boule or batard", "ingredients": ["Bread Flour: 500g", "Water: 375g", "Salt: 10g", "Active Dry Yeast: 7g"], "method": ["Mix all ingredients; autolyse 30 min.", "Knead 8–10 min until elastic.", "Rise 1–2 hr (3–4 hr if cold) until doubled.", "Shape into boule/batard; proof 30–60 min.", "Bake in preheated Dutch oven at 450°F: covered 25 min, uncovered 5 min.", "Cool 1 hr before slicing."], "notes": "Use steam (boiling water pan or dutch-oven cover) for better crust; score deeply for expansion.", "equipment": ["Dutch oven or baking stone", "bench scraper"]}', null),

('No-Knead White Bread', 'no-knead-white-bread', 'Seasonal', ARRAY['no-knead', 'winter', 'beginners', 'slow fermentation', 'everyday'], true, '66d74ee0-b848-4b4d-b37c-6197d5d01d66',
'{"season": "Winter", "holidays": [], "featuredDates": {"start": "01-01", "end": "03-31"}, "category": ["yeast bread"], "occasion": ["everyday"], "prepTime": "0 hours 10 minutes", "bakeTime": "0 hours 45 minutes", "totalTime": "13 hours 55 minutes", "difficulty": "beginner", "yield": "1 boule", "ingredients": ["Bread Flour: 500g", "Salt: 2 tsp", "Instant Yeast: 1/4 tsp", "Water: 375ml"], "method": ["Mix flour, salt, yeast; add water—shaggy dough.", "Cover; ferment 12–18 hr (up to 24 hr if cold).", "Turn out; fold dough twice; shape into ball.", "Proof 1–2 hr until puffy.", "Bake in 475°F preheated Dutch oven: covered 30 min, uncovered 10–15 min.", "Cool completely before slicing."], "notes": "For crisp crust, cool in Dutch oven with lid ajar; extend fermentation in cold kitchens.", "equipment": ["Dutch oven", "parchment paper"]}', null),

('Hanukkah Challah', 'hanukkah-challah', 'Seasonal', ARRAY['enriched', 'braided', 'holiday', 'Challah', 'Hanukkah'], true, '66d74ee0-b848-4b4d-b37c-6197d5d01d66',
'{"season": "Winter", "holidays": ["Hanukkah"], "featuredDates": {"start": "02-14", "end": "02-21"}, "category": ["enriched", "holiday bread"], "occasion": ["holiday specific", "celebration"], "prepTime": "0 hours 25 minutes", "bakeTime": "0 hours 30 minutes", "totalTime": "3 hours 40 minutes", "difficulty": "intermediate", "yield": "1 braided loaf", "ingredients": ["Bread Flour: 1kg", "Water: 500ml", "Active Dry Yeast: 14g", "Honey: 100g", "Salt: 1 tbsp", "Eggs: 4", "Vegetable Oil: 120ml", "Sesame or Poppy Seeds: 2 tbsp"], "method": ["Activate yeast in water+honey 5–10 min.", "Mix flour, salt, eggs, oil; knead 8–10 min.", "Rise 1.5 hr until doubled.", "Divide, braid, tuck ends.", "Proof 45 min until puffy.", "Egg wash; sprinkle seeds; bake 375°F 25–30 min.", "Cool 20 min before slicing."], "notes": "For extra shine, re-egg-wash halfway; flavor variations with raisins or savory seasoning.", "equipment": ["mixing bowl", "braiding surface"]}', null),

('Spring Herb Focaccia', 'spring-herb-focaccia', 'Seasonal', ARRAY['spring', 'focaccia', 'herbs', 'olive oil'], true, '66d74ee0-b848-4b4d-b37c-6197d5d01d66',
'{"season": "Spring", "holidays": [], "featuredDates": {"start": "04-01", "end": "05-31"}, "category": ["yeast bread"], "occasion": ["everyday"], "prepTime": "0 hours 20 minutes", "bakeTime": "0 hours 25 minutes", "totalTime": "3 hours", "difficulty": "intermediate", "yield": "1 large sheet", "ingredients": ["Bread Flour: 500g", "Water: 375ml", "Instant Yeast: 7g", "Salt: 10g", "Olive Oil: 60ml + extra for drizzling", "Fresh Rosemary: 2 tbsp, chopped", "Fresh Thyme: 1 tbsp, leaves", "Coarse Sea Salt: 1 tsp"], "method": ["Mix flour, water, yeast, salt until shaggy; rest 20 min.", "Knead 2–3 min; incorporate 60ml oil.", "Rise 1 hr until doubled.", "Press into oiled pan; dimple dough; drizzle oil.", "Sprinkle herbs & sea salt; proof 30 min.", "Bake 425°F 20–25 min until golden.", "Cool slightly before cutting."], "notes": "Use soft fingertips to avoid deflating; serve warm with olive oil dip.", "equipment": ["quarter-sheet pan", "mixing bowl"]}', null),

('Hot Cross Buns', 'hot-cross-buns', 'Seasonal', ARRAY['Easter', 'spring', 'enriched', 'spiced'], true, '66d74ee0-b848-4b4d-b37c-6197d5d01d66',
'{"season": "Spring", "holidays": ["Easter"], "featuredDates": {"start": "03-01", "end": "04-30"}, "category": ["enriched", "holiday bread"], "occasion": ["holiday specific", "celebration"], "prepTime": "0 hours 30 minutes", "bakeTime": "0 hours 20 minutes", "totalTime": "3 hours 30 minutes", "difficulty": "intermediate", "yield": "12 buns", "ingredients": ["Bread Flour: 500g", "Milk: 250ml", "Active Dry Yeast: 7g", "Sugar: 75g", "Butter: 50g, softened", "Salt: 1 tsp", "Egg: 1", "Raisins or Currants: 100g", "Mixed Spice: 1 tsp", "Flour Paste (for cross): 50g flour + water"], "method": ["Warm milk + yeast + 1 tsp sugar; froth 5 min.", "Mix flour, sugar, salt, spice; add yeast mix, egg, butter.", "Knead 8–10 min; add fruit in last 2 min.", "Rise 1.5 hr until doubled.", "Divide into 12; shape; proof 45 min.", "Pipe cross paste; bake 375°F 18–20 min.", "Glaze with warmed apricot jam."], "notes": "Chill dough 30 min before shaping for neater buns; vary dried fruit.", "equipment": ["12-cup muffin tin or baking sheet", "piping bag"]}', null);