-- Insert additional seasonal recipes
INSERT INTO public.recipes (title, slug, folder, tags, is_public, data, user_id) VALUES

-- Spring recipes
('Light Sourdough Batard', 'light-sourdough-batard', 'Seasonal', ARRAY['sourdough', 'artisan', 'batard', 'spring'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "03-01", "end": "05-31"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "30 minutes",
  "totalTime": "7 hours",
  "difficulty": "intermediate",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Water: 350ml (1 1/3 cups)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 10g (2 tsp)", "Unsweetened Cocoa Powder: 1 tsp (for dusting, optional)"],
  "method": ["Combine flour, water, and starter. Mix until hydrated. Rest 20-30 minutes (autolyse).", "Add salt, knead gently 5-8 minutes until smooth and elastic (passes windowpane test).", "Cover, rise 4-5 hours at room temperature, performing 3-4 sets of stretches and folds at 30-min intervals.", "Gently turn dough onto floured surface. Shape into batard by folding like a letter, then rolling into oval.", "Optionally dust surface with cocoa powder and rub in evenly.", "Place seam-side up in floured banneton. Cover, proof 1-2 hours until puffy.", "Preheat oven and Dutch oven to 475°F (245°C).", "Transfer dough to parchment, score with sharp blade.", "Bake covered 20 minutes, uncover and bake 10-15 minutes more.", "Cool on wire rack 30+ minutes before slicing."],
  "notes": "Cocoa powder adds visual contrast without flavor. Use gentle touch when shaping to preserve airy structure. Add ice cubes to skillet for steam.",
  "equipment": ["Dutch oven", "banneton"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Rustic Italian Ciabatta', 'rustic-italian-ciabatta', 'Seasonal', ARRAY['ciabatta', 'high hydration', 'artisan', 'italian'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "03-01", "end": "05-31"},
  "category": ["yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "25 minutes",
  "totalTime": "16 hours",
  "difficulty": "intermediate",
  "yield": "2 loaves",
  "ingredients": ["Poolish: Bread Flour: 150g (1 1/4 cups), Water: 150ml (2/3 cup), Instant Yeast: 1/8 tsp", "Main Dough: Bread Flour: 350g (2 3/4 cups), Water: 225ml (1 cup), Salt: 7g (2 1/4 tsp), Instant Yeast: 2g (1/2 tsp)"],
  "method": ["Make poolish: Mix ingredients, cover, ferment 12-18 hours at room temperature until bubbly.", "Combine main dough ingredients. Add poolish, mix thoroughly (dough will be very wet).", "Cover, rest 30 minutes. Perform 3 sets of stretch-and-folds every 30 minutes.", "Bulk ferment 1-2 hours until increased 50% with air bubbles.", "Gently turn dough onto well-floured surface. Divide into two pieces.", "Shape into rectangles by gentle stretching - avoid pressing out air bubbles.", "Transfer to floured parchment, dimple surface with fingertips.", "Proof 45-60 minutes until puffy.", "Preheat oven to 475°F (245°C) with baking stone.", "Slide loaves onto stone. Create steam with water pan.", "Bake 20-25 minutes until golden brown and hollow-sounding.", "Cool completely on wire rack."],
  "notes": "High hydration (80%) requires minimal handling. Use plenty of flour when shaping. Steam is essential for proper crust development.",
  "equipment": ["baking stone"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Easter Paska', 'easter-paska', 'Seasonal', ARRAY['easter', 'enriched', 'holiday', 'festive'], true, '{
  "season": "Spring",
  "holidays": ["Easter"],
  "featuredDates": {"start": "04-01", "end": "04-30"},
  "category": ["enriched", "holiday bread"],
  "occasion": ["celebration", "holiday specific"],
  "prepTime": "40 minutes",
  "bakeTime": "45 minutes",
  "totalTime": "4 hours",
  "difficulty": "intermediate",
  "yield": "1 large loaf",
  "ingredients": ["Bread Flour: 800g (6 1/2 cups)", "Milk: 360ml (1 1/2 cups), warm", "Active Dry Yeast: 14g (4 tsp)", "Eggs: 6", "Sugar: 200g (1 cup)", "Butter: 225g (1 cup), softened", "Salt: 15g (1 tbsp)", "Golden Raisins: 200g (1 1/3 cups), soaked", "Lemon Zest: 2 tbsp", "Orange Zest: 1 tbsp", "Vanilla Extract: 2 tsp", "Cardamom: 1 tsp"],
  "method": ["Activate yeast in warm milk with 1 tbsp sugar.", "Cream butter and sugar until light. Add eggs one at a time.", "Combine flour, salt, zests, and spices.", "Alternate adding flour mixture and yeast mixture to butter mixture.", "Knead 10-12 minutes until smooth and elastic.", "Drain raisins, fold into dough.", "Place in greased bowl, cover, rise 2 hours until doubled.", "Punch down, shape into round loaf or place in special Paska mold.", "Proof 1 hour until puffy.", "Preheat oven to 350°F (175°C).", "Brush with egg wash, bake 40-45 minutes until golden.", "Cool completely before decorating."],
  "notes": "Traditionally decorated with icing and sprinkles. Soak raisins in rum or juice for extra flavor. Use a Turk''s head mold for authentic shape.",
  "equipment": ["large mixing bowl", "stand mixer recommended"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Sourdough Bagels', 'sourdough-bagels', 'Seasonal', ARRAY['bagels', 'sourdough', 'overnight', 'breakfast'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "04-01", "end": "06-30"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "25 minutes",
  "totalTime": "18 hours",
  "difficulty": "intermediate",
  "yield": "8 bagels",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Water: 250ml (1 cup)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 15g (1 tbsp)", "Barley Malt Syrup: 30g (2 tbsp)", "Toppings: sesame seeds, poppy seeds, everything seasoning"],
  "method": ["Mix all ingredients except toppings. Knead 10 minutes.", "Rest 30 minutes. Divide into 8 portions.", "Shape into balls, poke hole through center, stretch to form bagel shape.", "Refrigerate overnight (12-16 hours).", "Preheat oven to 425°F (220°C). Bring large pot of water to boil with 1 tbsp baking soda.", "Boil bagels 1 minute per side. Remove with slotted spoon.", "Dip in toppings while wet.", "Bake 20-25 minutes until deeply golden.", "Cool on wire rack."],
  "notes": "For chewier texture, boil 2 minutes per side. Barley malt syrup gives authentic flavor and color. Freeze extras for toasting.",
  "equipment": ["slotted spoon", "baking sheets"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Cheddar and Chive Biscuits', 'cheddar-chive-biscuits', 'Seasonal', ARRAY['biscuits', 'cheddar', 'quick', 'spring'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "04-01", "end": "06-30"},
  "category": ["quick bread"],
  "occasion": ["everyday"],
  "prepTime": "15 minutes",
  "bakeTime": "20 minutes",
  "totalTime": "35 minutes",
  "difficulty": "beginner",
  "yield": "12 biscuits",
  "ingredients": ["All-purpose Flour: 300g (2 1/2 cups)", "Baking Powder: 15g (1 tbsp)", "Salt: 5g (1 tsp)", "Baking Soda: 2g (1/2 tsp)", "Cold Butter: 115g (1/2 cup), cubed", "Buttermilk: 240ml (1 cup), cold", "Sharp Cheddar: 150g (1 1/2 cups), shredded", "Fresh Chives: 30g (1/4 cup), chopped"],
  "method": ["Preheat oven to 425°F (220°C).", "Whisk dry ingredients together.", "Cut in butter until pea-sized crumbs form.", "Stir in cheese and chives.", "Add buttermilk, mix until just combined.", "Turn onto floured surface, pat to 1-inch thick.", "Cut with biscuit cutter, place on baking sheet.", "Bake 18-20 minutes until golden.", "Brush with melted butter before serving."],
  "notes": "Handle dough minimally for flaky layers. Freeze unbaked biscuits and bake directly from frozen (add 5 minutes). Serve with herb butter.",
  "equipment": ["biscuit cutter", "baking sheet"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Sourdough English Muffins', 'sourdough-english-muffins', 'Seasonal', ARRAY['english muffins', 'sourdough', 'breakfast', 'overnight'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "04-01", "end": "06-30"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "15 minutes",
  "totalTime": "18 hours",
  "difficulty": "intermediate",
  "yield": "12 muffins",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Milk: 240ml (1 cup), warm", "Active Sourdough Starter: 150g (1/2 cup)", "Honey: 30g (2 tbsp)", "Salt: 10g (2 tsp)", "Baking Soda: 5g (1 tsp)", "Cornmeal: for dusting"],
  "method": ["Mix all ingredients except cornmeal. Knead 5 minutes.", "Refrigerate overnight (12-16 hours).", "Turn dough onto cornmeal-dusted surface.", "Roll to 1/2-inch thick. Cut with 3-inch ring cutter.", "Dust with cornmeal, cover, proof 1 hour.", "Preheat griddle or skillet to medium-low (300°F/150°C).", "Cook 8-10 minutes per side until golden and internal temp 200°F.", "Cool completely on rack. Fork-split before toasting."],
  "notes": "Low slow cooking creates perfect nooks and crannies. Freeze extras. For whole wheat version, substitute 50% flour with whole wheat.",
  "equipment": ["griddle or skillet", "ring cutter"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Honey Oatmeal Bread', 'honey-oatmeal-bread', 'Seasonal', ARRAY['oatmeal', 'honey', 'sandwich bread', 'spring'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "04-01", "end": "06-30"},
  "category": ["yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "25 minutes",
  "bakeTime": "35 minutes",
  "totalTime": "3 hours",
  "difficulty": "beginner",
  "yield": "1 loaf",
  "ingredients": ["Rolled Oats: 100g (1 cup)", "Boiling Water: 240ml (1 cup)", "Bread Flour: 400g (3 1/3 cups)", "Active Dry Yeast: 7g (2 1/4 tsp)", "Honey: 80g (1/4 cup)", "Salt: 10g (2 tsp)", "Butter: 30g (2 tbsp), softened", "Additional Oats: for topping"],
  "method": ["Pour boiling water over oats, let cool to lukewarm.", "Add yeast, honey, butter, and 1 cup flour. Mix, let sit 15 minutes.", "Add salt and remaining flour. Knead 8-10 minutes.", "Rise 1.5 hours until doubled.", "Shape into loaf, place in 9x5-inch pan.", "Brush with water, sprinkle with oats.", "Proof 45-60 minutes until above rim.", "Preheat oven to 350°F (175°C).", "Bake 30-35 minutes until internal temp 190°F.", "Cool completely before slicing."],
  "notes": "Soaking oats creates tender crumb. For variation, add raisins or nuts. Makes excellent toast with cinnamon sugar.",
  "equipment": ["9x5-inch loaf pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Rosemary Garlic Focaccia', 'rosemary-garlic-focaccia', 'Seasonal', ARRAY['focaccia', 'rosemary', 'garlic', 'spring'], true, '{
  "season": "Spring",
  "holidays": [],
  "featuredDates": {"start": "04-01", "end": "06-30"},
  "category": ["yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "20 minutes",
  "bakeTime": "25 minutes",
  "totalTime": "3 hours",
  "difficulty": "beginner",
  "yield": "1 large focaccia",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Warm Water: 375ml (1 1/2 cups + 1 tbsp)", "Active Dry Yeast: 7g (2 1/4 tsp)", "Olive Oil: 90ml (6 tbsp), divided", "Salt: 10g (2 tsp)", "Fresh Rosemary: 3 tbsp, chopped", "Garlic: 4 cloves, minced", "Flaky Sea Salt: for topping"],
  "method": ["Activate yeast in warm water with pinch of sugar.", "Mix flour, salt, yeast mixture, and 3 tbsp olive oil.", "Knead 5-7 minutes until smooth.", "Place in oiled bowl, rise 1 hour until doubled.", "Press into oiled 9x13-inch pan, dimple surface.", "Sauté garlic in 2 tbsp olive oil until fragrant.", "Sprinkle rosemary and garlic over dough.", "Proof 30 minutes.", "Preheat oven to 425°F (220°C).", "Drizzle with remaining oil, sprinkle sea salt.", "Bake 20-25 minutes until golden.", "Cool slightly before serving."],
  "notes": "Infuse olive oil with rosemary for extra flavor. Add sun-dried tomatoes for variation. Serve warm with balsamic reduction.",
  "equipment": ["9x13-inch baking pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

-- Summer recipes
('Olive and Rosemary Focaccia', 'olive-rosemary-focaccia', 'Seasonal', ARRAY['focaccia', 'olive', 'rosemary', 'mediterranean', 'summer'], true, '{
  "season": "Summer",
  "holidays": [],
  "featuredDates": {"start": "07-01", "end": "09-30"},
  "category": ["yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "20 minutes",
  "bakeTime": "25 minutes",
  "totalTime": "3 hours",
  "difficulty": "beginner",
  "yield": "1 large focaccia",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Warm Water: 375ml (1 1/2 cups + 1 tbsp)", "Active Dry Yeast: 7g (2 1/4 tsp)", "Olive Oil: 90ml (6 tbsp)", "Salt: 10g (2 tsp)", "Kalamata Olives: 150g (1 cup), pitted and halved", "Fresh Rosemary: 2 tbsp, chopped", "Flaky Sea Salt: for topping"],
  "method": ["Activate yeast in warm water with pinch of sugar.", "Mix flour, salt, yeast mixture, and 3 tbsp olive oil.", "Knead 5-7 minutes until smooth.", "Place in oiled bowl, rise 1 hour until doubled.", "Press into oiled 9x13-inch pan, dimple surface.", "Press olives into dough, sprinkle rosemary.", "Proof 30 minutes.", "Preheat oven to 425°F (220°C).", "Drizzle with 3 tbsp olive oil, sprinkle sea salt.", "Bake 20-25 minutes until golden.", "Drizzle with remaining oil before serving."],
  "notes": "Use brine-cured olives for best flavor. Add sun-dried tomatoes for variation. Serve with balsamic and olive oil for dipping.",
  "equipment": ["9x13-inch baking pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Sourdough Pizza Dough', 'sourdough-pizza-dough', 'Seasonal', ARRAY['pizza', 'sourdough', 'grilling', 'overnight', 'summer'], true, '{
  "season": "Summer",
  "holidays": [],
  "featuredDates": {"start": "07-01", "end": "09-30"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "15 minutes",
  "totalTime": "24 hours",
  "difficulty": "intermediate",
  "yield": "4 pizzas",
  "ingredients": ["Bread Flour: 600g (5 cups)", "Water: 360ml (1 1/2 cups)", "Active Sourdough Starter: 120g (1/2 cup)", "Salt: 12g (2 tsp)", "Olive Oil: 30ml (2 tbsp)"],
  "method": ["Mix all ingredients until shaggy dough forms.", "Rest 30 minutes. Knead briefly until smooth.", "Divide into 4 balls, place in oiled containers.", "Refrigerate 24-72 hours.", "Remove from fridge 2 hours before baking.", "Preheat oven with pizza stone to 500°F (260°C).", "Stretch dough to desired thinness.", "Add toppings, bake 10-15 minutes until crisp."],
  "notes": "Long fermentation develops flavor. For grill cooking, preheat to high and cook 2-3 minutes per side. Freeze dough balls for future use.",
  "equipment": ["pizza stone"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Jalapeño Cheddar Cornbread', 'jalapeno-cheddar-cornbread', 'Seasonal', ARRAY['cornbread', 'jalapeno', 'cheese', 'quick', 'summer'], true, '{
  "season": "Summer",
  "holidays": ["July 4th"],
  "featuredDates": {"start": "07-01", "end": "08-31"},
  "category": ["quick bread"],
  "occasion": ["celebration"],
  "prepTime": "15 minutes",
  "bakeTime": "25 minutes",
  "totalTime": "40 minutes",
  "difficulty": "beginner",
  "yield": "9x9-inch pan",
  "ingredients": ["Cornmeal: 200g (1 1/2 cups)", "All-purpose Flour: 150g (1 1/4 cups)", "Baking Powder: 15g (1 tbsp)", "Baking Soda: 5g (1 tsp)", "Salt: 5g (1 tsp)", "Buttermilk: 360ml (1 1/2 cups)", "Eggs: 2", "Honey: 80g (1/4 cup)", "Melted Butter: 115g (1/2 cup)", "Cheddar Cheese: 150g (1 1/2 cups), shredded", "Jalapeños: 3, seeded and diced"],
  "method": ["Preheat oven to 400°F (200°C). Grease 9x9-inch pan.", "Whisk dry ingredients together.", "Mix buttermilk, eggs, honey, and butter.", "Combine wet and dry ingredients until just mixed.", "Fold in cheese and jalapeños.", "Pour into pan, bake 20-25 minutes until golden.", "Cool 10 minutes before serving."],
  "notes": "For extra kick, include some jalapeño seeds. Serve warm with chili or barbecue. Top with extra cheese last 5 minutes of baking.",
  "equipment": ["9x9-inch baking pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Sun-Dried Tomato and Feta Bread', 'sun-dried-tomato-feta-bread', 'Seasonal', ARRAY['savory', 'tomato', 'feta', 'mediterranean', 'summer'], true, '{
  "season": "Summer",
  "holidays": [],
  "featuredDates": {"start": "07-01", "end": "08-31"},
  "category": ["yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "40 minutes",
  "totalTime": "3 hours",
  "difficulty": "intermediate",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Water: 300ml (1 1/4 cups), warm", "Active Dry Yeast: 7g (2 1/4 tsp)", "Salt: 10g (2 tsp)", "Olive Oil: 30ml (2 tbsp)", "Sun-Dried Tomatoes: 100g (3/4 cup), chopped", "Feta Cheese: 150g (1 cup), crumbled", "Fresh Basil: 1/4 cup, chopped"],
  "method": ["Soak tomatoes in hot water 10 minutes, drain.", "Activate yeast in warm water.", "Mix flour, salt, yeast mixture, and oil.", "Knead 8 minutes until smooth.", "Add tomatoes, feta, and basil during last minute of kneading.", "Rise 1.5 hours until doubled.", "Shape into boule or batard.", "Proof 45 minutes.", "Preheat oven to 425°F (220°C) with baking stone.", "Score, bake 20 minutes.", "Reduce to 375°F (190°C), bake 15-20 minutes more.", "Cool before slicing."],
  "notes": "Use oil-packed tomatoes for richer flavor. For crisp crust, add steam during first 10 minutes of baking. Serve with olive oil dip.",
  "equipment": ["baking stone"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Apricot Almond Sourdough', 'apricot-almond-sourdough', 'Seasonal', ARRAY['sourdough', 'apricot', 'almond', 'summer', 'overnight'], true, '{
  "season": "Summer",
  "holidays": [],
  "featuredDates": {"start": "07-01", "end": "08-31"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "40 minutes",
  "bakeTime": "45 minutes",
  "totalTime": "18 hours",
  "difficulty": "advanced",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 450g (3 3/4 cups)", "Whole Wheat Flour: 50g (1/3 cup)", "Water: 375g (1.6 cups)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 10g (2 tsp)", "Dried Apricots: 150g (1 cup), chopped", "Slivered Almonds: 100g (1 cup), toasted", "Amaretto: 30ml (2 tbsp)"],
  "method": ["Soak apricots in Amaretto 30 minutes, drain.", "Mix flours and water, autolyse 30 minutes.", "Add starter and salt, mix thoroughly.", "Stretch-and-folds over 2 hours.", "Add apricots and almonds during last fold.", "Bulk ferment 4-6 hours.", "Shape into batard.", "Proof in banneton 1-2 hours or overnight refrigerated.", "Preheat Dutch oven to 475°F (245°C).", "Score, bake covered 20 minutes.", "Uncover, bake 20-25 minutes more.", "Cool completely before slicing."],
  "notes": "Toast almonds for enhanced flavor. Glaze with apricot jam after baking for shine. Perfect for summer cheese boards.",
  "equipment": ["Dutch oven", "banneton"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Cherry Vanilla Sourdough', 'cherry-vanilla-sourdough', 'Seasonal', ARRAY['sourdough', 'cherry', 'vanilla', 'summer', 'overnight'], true, '{
  "season": "Summer",
  "holidays": [],
  "featuredDates": {"start": "07-01", "end": "08-31"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "40 minutes",
  "bakeTime": "45 minutes",
  "totalTime": "18 hours",
  "difficulty": "advanced",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Water: 375g (1.6 cups)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 10g (2 tsp)", "Dried Cherries: 150g (1 cup), chopped", "Vanilla Bean: 1, seeds scraped", "Almond Extract: 1 tsp (optional)"],
  "method": ["Soak cherries in hot water 15 minutes, drain.", "Mix flour and water, autolyse 30 minutes.", "Add starter, salt, vanilla seeds, and almond extract.", "Mix thoroughly.", "Stretch-and-folds over 2 hours.", "Add cherries during last fold.", "Bulk ferment 4-6 hours.", "Shape into boule.", "Proof in banneton 1-2 hours or overnight refrigerated.", "Preheat Dutch oven to 475°F (245°C).", "Score, bake covered 20 minutes.", "Uncover, bake 20-25 minutes more.", "Cool completely before slicing."],
  "notes": "Use tart cherries for best flavor. Soak cherries in kirsch for adult version. Glaze with vanilla icing after cooling.",
  "equipment": ["Dutch oven", "banneton"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Blueberry Lemon Scones', 'blueberry-lemon-scones', 'Seasonal', ARRAY['scones', 'blueberry', 'lemon', 'quick', 'summer'], true, '{
  "season": "Summer",
  "holidays": [],
  "featuredDates": {"start": "07-01", "end": "08-31"},
  "category": ["quick bread"],
  "occasion": ["everyday"],
  "prepTime": "20 minutes",
  "bakeTime": "20 minutes",
  "totalTime": "40 minutes",
  "difficulty": "beginner",
  "yield": "8 scones",
  "ingredients": ["All-purpose Flour: 300g (2 1/2 cups)", "Baking Powder: 15g (1 tbsp)", "Salt: 5g (1 tsp)", "Sugar: 50g (1/4 cup)", "Lemon Zest: 1 tbsp", "Cold Butter: 115g (1/2 cup), cubed", "Fresh Blueberries: 150g (1 cup)", "Heavy Cream: 180ml (3/4 cup)", "Egg: 1, for wash", "Lemon Glaze: Powdered Sugar: 120g (1 cup), Lemon Juice: 2-3 tbsp"],
  "method": ["Preheat oven to 400°F (200°C).", "Whisk dry ingredients and lemon zest.", "Cut in butter until pea-sized crumbs.", "Gently fold in blueberries.", "Add cream, mix until just combined.", "Pat into 8-inch circle, cut into 8 wedges.", "Place on baking sheet, brush with egg wash.", "Bake 18-20 minutes until golden.", "Cool 10 minutes, drizzle with glaze."],
  "notes": "Freeze butter and grate for flakier scones. Toss blueberries in flour to prevent sinking. Substitute with raspberries or blackberries.",
  "equipment": ["baking sheet"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

-- Fall recipes
('Fig and Walnut Sourdough', 'fig-walnut-sourdough', 'Seasonal', ARRAY['sourdough', 'fig', 'walnut', 'holiday', 'overnight'], true, '{
  "season": "Fall",
  "holidays": ["Thanksgiving"],
  "featuredDates": {"start": "10-01", "end": "11-30"},
  "category": ["sourdough"],
  "occasion": ["celebration"],
  "prepTime": "40 minutes",
  "bakeTime": "45 minutes",
  "totalTime": "18 hours",
  "difficulty": "advanced",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 450g (3 3/4 cups)", "Whole Wheat Flour: 50g (1/3 cup)", "Water: 375g (1.6 cups)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 10g (2 tsp)", "Dried Figs: 150g (1 cup), chopped", "Walnuts: 100g (1 cup), toasted and chopped", "Orange Zest: 1 tbsp", "Fennel Seeds: 1 tsp (optional)"],
  "method": ["Mix flours and water, autolyse 30 minutes.", "Add starter and salt, mix thoroughly.", "Perform stretch-and-folds over 2 hours.", "Add figs, walnuts, zest, and seeds during last fold.", "Bulk ferment 4-6 hours total.", "Shape into boule or batard.", "Proof in banneton 1-2 hours or overnight refrigerated.", "Preheat Dutch oven to 475°F (245°C).", "Score decoratively, bake covered 20 minutes.", "Uncover, bake 20-25 minutes more.", "Cool completely before slicing."],
  "notes": "Soak figs in warm water or port wine for 30 minutes if dry. Toast walnuts for deeper flavor. Pairs well with blue cheese.",
  "equipment": ["Dutch oven", "banneton"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Multigrain Sandwich Loaf', 'multigrain-sandwich-loaf', 'Seasonal', ARRAY['multigrain', 'whole grain', 'sandwich bread', 'fall'], true, '{
  "season": "Fall",
  "holidays": [],
  "featuredDates": {"start": "09-01", "end": "11-30"},
  "category": ["whole grain", "yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "30 minutes",
  "bakeTime": "40 minutes",
  "totalTime": "3.5 hours",
  "difficulty": "intermediate",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 300g (2 1/2 cups)", "Whole Wheat Flour: 150g (1 1/4 cups)", "Rolled Oats: 50g (1/2 cup)", "Warm Water: 375ml (1 1/2 cups)", "Active Dry Yeast: 7g (2 1/4 tsp)", "Honey: 60g (3 tbsp)", "Salt: 10g (2 tsp)", "Butter: 30g (2 tbsp), softened", "Mixed Seeds: 50g (1/3 cup) - sunflower, flax, sesame, pumpkin"],
  "method": ["Combine oats and 125ml (1/2 cup) water, simmer 5 minutes, cool.", "Activate yeast in remaining warm water with honey.", "Mix flours, salt, and seeds.", "Add yeast mixture, oat mixture, and butter.", "Knead 8-10 minutes until smooth.", "Rise 1.5 hours until doubled.", "Shape into loaf, place in 9x5-inch pan.", "Proof 45-60 minutes until above rim.", "Preheat oven to 375°F (190°C).", "Brush with water, sprinkle additional seeds.", "Bake 35-40 minutes until internal temperature 190°F.", "Cool completely before slicing."],
  "notes": "Soak seeds overnight for easier digestion. For softer crust, brush with butter after baking. Makes excellent toast.",
  "equipment": ["9x5-inch loaf pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Caramelized Onion and Gruyère Fougasse', 'caramelized-onion-gruyere-fougasse', 'Seasonal', ARRAY['fougasse', 'savory', 'cheese', 'onion', 'fall'], true, '{
  "season": "Fall",
  "holidays": [],
  "featuredDates": {"start": "10-01", "end": "11-30"},
  "category": ["yeast bread"],
  "occasion": ["celebration"],
  "prepTime": "40 minutes",
  "bakeTime": "20 minutes",
  "totalTime": "3 hours",
  "difficulty": "intermediate",
  "yield": "2 loaves",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Water: 300ml (1 1/4 cups), warm", "Active Dry Yeast: 7g (2 1/4 tsp)", "Salt: 10g (2 tsp)", "Olive Oil: 30ml (2 tbsp)", "Caramelized Onions: 200g (1 1/2 cups)", "Gruyère Cheese: 150g (1 1/2 cups), grated", "Fresh Thyme: 1 tbsp, chopped"],
  "method": ["Caramelize onions: Cook sliced onions with olive oil over low heat 30 minutes until golden.", "Mix flour, yeast, salt. Add water and oil, mix until shaggy dough.", "Knead 8 minutes until smooth.", "Add onions, cheese, and thyme during last minute of kneading.", "Rise 1.5 hours until doubled.", "Divide in half. Roll each into oval.", "Cut slashes to create leaf pattern.", "Proof 30 minutes.", "Preheat oven to 425°F (220°C).", "Bake 18-20 minutes until golden.", "Brush with olive oil before serving."],
  "notes": "Make decorative cuts before proofing. Serve warm. Add bacon bits for extra flavor. Freezes well.",
  "equipment": ["baking stone"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Spiced Pear Bread', 'spiced-pear-bread', 'Seasonal', ARRAY['pear', 'spiced', 'quick bread', 'fall', 'thanksgiving'], true, '{
  "season": "Fall",
  "holidays": ["Thanksgiving"],
  "featuredDates": {"start": "10-01", "end": "11-30"},
  "category": ["quick bread"],
  "occasion": ["celebration"],
  "prepTime": "25 minutes",
  "bakeTime": "60 minutes",
  "totalTime": "1.5 hours",
  "difficulty": "beginner",
  "yield": "1 loaf",
  "ingredients": ["All-purpose Flour: 300g (2 1/2 cups)", "Baking Powder: 10g (2 tsp)", "Baking Soda: 5g (1 tsp)", "Salt: 5g (1 tsp)", "Cinnamon: 2 tsp", "Nutmeg: 1/2 tsp", "Ginger: 1/2 tsp", "Vegetable Oil: 120ml (1/2 cup)", "Brown Sugar: 200g (1 cup)", "Eggs: 2", "Vanilla Extract: 2 tsp", "Ripe Pears: 400g (3 cups), peeled and diced", "Walnuts: 100g (1 cup), chopped (optional)"],
  "method": ["Preheat oven to 350°F (175°C). Grease 9x5-inch loaf pan.", "Whisk dry ingredients together.", "Beat oil, sugar, eggs, and vanilla until smooth.", "Add dry ingredients, mix until just combined.", "Fold in pears and walnuts.", "Pour into pan, bake 55-65 minutes until tester clean.", "Cool in pan 10 minutes, then on rack."],
  "notes": "Use Bartlett or Anjou pears. For extra moisture, add 1/4 cup pear brandy. Glaze with cream cheese frosting if desired.",
  "equipment": ["9x5-inch loaf pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Sourdough Pretzels', 'sourdough-pretzels', 'Seasonal', ARRAY['pretzels', 'sourdough', 'overnight', 'fall'], true, '{
  "season": "Fall",
  "holidays": [],
  "featuredDates": {"start": "10-01", "end": "11-30"},
  "category": ["sourdough"],
  "occasion": ["everyday"],
  "prepTime": "40 minutes",
  "bakeTime": "20 minutes",
  "totalTime": "18 hours",
  "difficulty": "intermediate",
  "yield": "8 pretzels",
  "ingredients": ["Bread Flour: 500g (4 cups)", "Water: 250ml (1 cup)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 10g (2 tsp)", "Butter: 30g (2 tbsp), softened", "Baking Soda: 60g (1/4 cup) for boiling", "Coarse Salt: for topping"],
  "method": ["Mix all ingredients except baking soda and coarse salt. Knead 8 minutes.", "Refrigerate overnight (12-16 hours).", "Divide into 8 pieces. Roll into 20-inch ropes.", "Shape into pretzels. Freeze 30 minutes.", "Preheat oven to 425°F (220°C). Bring 8 cups water to boil with baking soda.", "Boil pretzels 30 seconds per side. Remove with slotted spoon.", "Sprinkle with coarse salt.", "Bake 15-18 minutes until deep brown.", "Cool on wire rack."],
  "notes": "For authentic flavor, use food-grade lye instead of baking soda (use caution). Brush with butter after baking. Serve with beer cheese dip.",
  "equipment": ["slotted spoon", "baking sheets"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Buttermilk Potato Rolls', 'buttermilk-potato-rolls', 'Seasonal', ARRAY['potato', 'rolls', 'thanksgiving', 'buttermilk'], true, '{
  "season": "Fall",
  "holidays": ["Thanksgiving"],
  "featuredDates": {"start": "11-01", "end": "11-30"},
  "category": ["yeast bread"],
  "occasion": ["celebration"],
  "prepTime": "35 minutes",
  "bakeTime": "20 minutes",
  "totalTime": "3 hours",
  "difficulty": "intermediate",
  "yield": "24 rolls",
  "ingredients": ["Mashed Potatoes: 300g (1 1/2 cups)", "Buttermilk: 360ml (1 1/2 cups), warm", "Active Dry Yeast: 14g (4 tsp)", "Honey: 60g (3 tbsp)", "Butter: 100g (1/2 cup), softened", "Eggs: 2", "Bread Flour: 800g (6 1/2 cups)", "Salt: 15g (1 tbsp)"],
  "method": ["Combine warm buttermilk, yeast, and honey. Sit until foamy.", "Mix mashed potatoes, butter, and eggs.", "Combine with yeast mixture.", "Add flour and salt, knead 8-10 minutes.", "Rise 1.5 hours until doubled.", "Divide into 24 pieces, shape into balls.", "Place in greased pans, proof 45 minutes.", "Preheat oven to 375°F (190°C).", "Brush with egg wash, bake 18-20 minutes.", "Brush with butter after baking."],
  "notes": "Use leftover mashed potatoes. Potato creates ultra-soft texture. Freeze unbaked rolls and bake directly from frozen (add 5 minutes).",
  "equipment": ["two 9x13-inch baking pans"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Millet and Flaxseed Bread', 'millet-flaxseed-bread', 'Seasonal', ARRAY['millet', 'flaxseed', 'whole grain', 'fall'], true, '{
  "season": "Fall",
  "holidays": [],
  "featuredDates": {"start": "09-01", "end": "11-30"},
  "category": ["whole grain", "yeast bread"],
  "occasion": ["everyday"],
  "prepTime": "35 minutes",
  "bakeTime": "45 minutes",
  "totalTime": "4 hours",
  "difficulty": "intermediate",
  "yield": "1 loaf",
  "ingredients": ["Bread Flour: 400g (3 1/3 cups)", "Whole Wheat Flour: 100g (3/4 cup)", "Cooked Millet: 150g (3/4 cup)", "Flaxseeds: 50g (1/3 cup)", "Water: 450g (2 cups), divided", "Active Dry Yeast: 7g (2 1/4 tsp)", "Honey: 60g (3 tbsp)", "Salt: 10g (2 tsp)", "Olive Oil: 30ml (2 tbsp)"],
  "method": ["Soak flaxseeds in 150g (2/3 cup) water for 30 minutes.", "Activate yeast in 100g (1/3 cup) warm water with honey.", "Mix flours, salt, cooked millet, flaxseed mixture.", "Add yeast mixture, oil, and remaining water.", "Knead 8-10 minutes until smooth.", "Rise 1.5 hours until doubled.", "Shape into loaf, place in 9x5-inch pan.", "Proof 45-60 minutes.", "Preheat oven to 375°F (190°C).", "Bake 40-45 minutes until internal temp 200°F.", "Cool completely before slicing."],
  "notes": "Millet adds pleasant crunch. Toast flaxseeds for nuttier flavor. Excellent for avocado toast. Stores well for 5 days.",
  "equipment": ["9x5-inch loaf pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

-- Winter recipes
('Stollen', 'stollen', 'Seasonal', ARRAY['christmas', 'german', 'marzipan', 'holiday'], true, '{
  "season": "Winter",
  "holidays": ["Christmas"],
  "featuredDates": {"start": "12-01", "end": "12-31"},
  "category": ["enriched", "holiday bread"],
  "occasion": ["celebration", "holiday specific"],
  "prepTime": "40 minutes",
  "bakeTime": "60 minutes",
  "totalTime": "4 hours",
  "difficulty": "intermediate",
  "yield": "2 loaves",
  "ingredients": ["Bread Flour: 800g (6 1/2 cups)", "Milk: 300ml (1 1/4 cups), warm", "Active Dry Yeast: 14g (4 tsp)", "Sugar: 150g (3/4 cup)", "Butter: 225g (1 cup), softened", "Eggs: 3", "Salt: 10g (2 tsp)", "Lemon Zest: 2 tbsp", "Cardamom: 2 tsp", "Candied Citrus Peel: 150g (1 cup)", "Raisins: 300g (2 cups), soaked", "Almonds: 150g (1 cup), slivered", "Marzipan: 300g (10.5 oz)", "Melted Butter and Powdered Sugar for finishing"],
  "method": ["Activate yeast in warm milk with 1 tbsp sugar.", "Cream butter and sugar. Add eggs one at a time.", "Combine flour, salt, zest, and cardamom.", "Alternate adding flour mixture and yeast mixture to butter mixture.", "Knead 8-10 minutes until smooth.", "Drain raisins, fold in with citrus peel and almonds.", "Rise 1.5 hours until doubled.", "Divide dough in half. Roll each into oval.", "Roll marzipan into logs, place off-center on each oval.", "Fold dough over marzipan, sealing edges.", "Proof 45 minutes until puffy.", "Preheat oven to 350°F (175°C).", "Bake 50-60 minutes until golden.", "Brush with melted butter, dust heavily with powdered sugar.", "Cool completely before slicing."],
  "notes": "Aged 1-2 weeks for best flavor. Wrap tightly and store in cool place. Soak raisins in rum for authentic flavor.",
  "equipment": ["stand mixer recommended"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Rye Sourdough with Caraway', 'rye-sourdough-caraway', 'Seasonal', ARRAY['rye', 'sourdough', 'caraway', 'whole grain', 'winter'], true, '{
  "season": "Winter",
  "holidays": [],
  "featuredDates": {"start": "01-01", "end": "03-31"},
  "category": ["sourdough", "whole grain"],
  "occasion": ["everyday"],
  "prepTime": "40 minutes",
  "bakeTime": "45 minutes",
  "totalTime": "18 hours",
  "difficulty": "advanced",
  "yield": "1 loaf",
  "ingredients": ["Rye Flour: 300g (2 1/2 cups)", "Bread Flour: 200g (1 2/3 cups)", "Water: 375g (1.6 cups)", "Active Sourdough Starter: 100g (1/2 cup)", "Salt: 10g (2 tsp)", "Caraway Seeds: 15g (2 tbsp)", "Molasses: 30g (2 tbsp)"],
  "method": ["Mix flours and water, autolyse 30 minutes.", "Add starter, salt, caraway, and molasses.", "Mix thoroughly (dough will be sticky).", "Bulk ferment 4-6 hours with minimal handling.", "Shape into boule.", "Proof in banneton 1-2 hours or overnight refrigerated.", "Preheat oven to 475°F (245°C) with Dutch oven.", "Score deeply, bake covered 20 minutes.", "Uncover, reduce to 425°F (220°C), bake 20-25 minutes more.", "Cool completely before slicing (minimum 4 hours)."],
  "notes": "High hydration requires minimal shaping. For traditional flavor, use dark rye flour. Best sliced thin for open-faced sandwiches.",
  "equipment": ["Dutch oven", "banneton"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Maple Walnut Sticky Buns', 'maple-walnut-sticky-buns', 'Seasonal', ARRAY['sticky buns', 'maple', 'walnut', 'holiday', 'enriched'], true, '{
  "season": "Winter",
  "holidays": ["Christmas"],
  "featuredDates": {"start": "12-01", "end": "12-31"},
  "category": ["enriched", "yeast bread"],
  "occasion": ["celebration"],
  "prepTime": "40 minutes",
  "bakeTime": "30 minutes",
  "totalTime": "4 hours",
  "difficulty": "intermediate",
  "yield": "12 buns",
  "ingredients": ["Dough: Bread Flour: 500g (4 cups), Milk: 240ml (1 cup), Active Dry Yeast: 7g (2 1/4 tsp), Sugar: 75g (1/3 cup), Butter: 100g (1/2 cup), Eggs: 2, Salt: 5g (1 tsp)", "Filling: Brown Sugar: 200g (1 cup), Cinnamon: 2 tbsp, Butter: 100g (1/2 cup), Chopped Walnuts: 150g (1 1/2 cups)", "Topping: Maple Syrup: 180ml (3/4 cup), Butter: 115g (1/2 cup), Brown Sugar: 200g (1 cup)"],
  "method": ["Make dough: Activate yeast in warm milk with sugar.", "Mix flour, salt. Add yeast mixture, butter, eggs.", "Knead 8-10 minutes. Rise 1.5 hours until doubled.", "Prepare topping: Melt butter, mix with maple syrup and brown sugar. Pour into 9x13-inch pan. Sprinkle walnuts.", "Roll dough to 16x12-inch rectangle.", "Spread filling butter, sprinkle cinnamon sugar and walnuts.", "Roll tightly, cut into 12 slices.", "Place cut-side down in pan. Rise 45 minutes.", "Preheat oven to 375°F (190°C).", "Bake 25-30 minutes until golden.", "Invert onto serving plate while warm."],
  "notes": "Use dark maple syrup for best flavor. Make ahead: Refrigerate after shaping, bake in morning. Add orange zest to filling for brightness.",
  "equipment": ["9x13-inch baking pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66'),

('Pumpernickel Bread', 'pumpernickel-bread', 'Seasonal', ARRAY['pumpernickel', 'rye', 'whole grain', 'winter', 'overnight'], true, '{
  "season": "Winter",
  "holidays": [],
  "featuredDates": {"start": "01-01", "end": "03-31"},
  "category": ["yeast bread", "whole grain"],
  "occasion": ["everyday"],
  "prepTime": "40 minutes",
  "bakeTime": "60 minutes",
  "totalTime": "24 hours",
  "difficulty": "advanced",
  "yield": "1 loaf",
  "ingredients": ["Rye Berries: 100g (1/2 cup)", "Water: for soaking", "Pumpernickel Flour: 300g (2 1/2 cups)", "Bread Flour: 200g (1 2/3 cups)", "Active Dry Yeast: 7g (2 1/4 tsp)", "Molasses: 80g (1/4 cup)", "Cocoa Powder: 30g (1/4 cup)", "Salt: 15g (1 tbsp)", "Caraway Seeds: 15g (2 tbsp)", "Coffee: 240ml (1 cup), strong brewed, cooled"],
  "method": ["Soak rye berries overnight in water.", "Drain, simmer 1 hour until tender. Drain and cool.", "Mix flours, yeast, cocoa, salt, caraway.", "Add molasses and coffee, mix until shaggy dough.", "Knead 10 minutes. Fold in rye berries.", "Rise 2 hours until puffy.", "Shape into loaf, place in 9x5-inch pan.", "Proof 1.5 hours.", "Preheat oven to 325°F (160°C).", "Bake 50-60 minutes until internal temp 200°F.", "Wrap in foil, cool in turned-off oven 2 hours.", "Cool completely before slicing."],
  "notes": "Long cool-down develops flavor. Best made 2-3 days before eating. For authentic texture, use coarse rye meal.",
  "equipment": ["9x5-inch loaf pan"]
}', '66d74ee0-b848-4b4d-b37c-6197d5d01d66');