-- Attempt to update all installed extensions to recommended versions (best-effort)
begin;

DO $$
BEGIN
  -- Safe best-effort updates; ignore if already latest or not permitted
  BEGIN EXECUTE 'ALTER EXTENSION citext UPDATE';            EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION pg_graphql UPDATE';        EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION pg_stat_statements UPDATE';EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION pgcrypto UPDATE';          EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION pgjwt UPDATE';             EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION pgsodium UPDATE';          EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION supabase_vault UPDATE';    EXCEPTION WHEN OTHERS THEN NULL; END;
  BEGIN EXECUTE 'ALTER EXTENSION "uuid-ossp" UPDATE';      EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;

commit;